### ISSUE TITLE
9.6-1.5 tag not available on docker hub

### ISSUE THREAD

**Issue by machineloop** [clkao/docker-postgres-plv8#16]
I get the following output when I try to pull 9.6-1.5:

> Pulling db (clkao/postgres-plv8:9.6-1.5)...
> Pulling repository docker.io/clkao/postgres-plv8
> ERROR: Tag 9.6-1.5 not found in repository docker.io/clkao/postgres-plv8

Thanks for maintaining this, much appreciated!

**Comment by ruimarinho** [comment]
@clkao can you handle this?

**Comment by clkao** [comment]
9.6-1.5 should now be available.
