### ISSUE TITLE
Wish request: Postgres 10

### ISSUE THREAD

**Issue by egandro** [clkao/docker-postgres-plv8#27]
Hello!

Can you please update this nice pice of work for the recent Postgres 10?

Thank you!

**Comment by egandro** [comment]
created pull request

**Comment by pdaher** [comment]
Any estimate date for having this closed?

**Comment by jmls** [comment]
I would also like to know - thanks

**Comment by ruimarinho** [comment]
Closed by https://github.com/clkao/docker-postgres-plv8/pull/29.

**Comment by mrmurphy** [comment]
I don't see the 10-2 tag on docker hub, anyone else? the :latest tag points to 9.6 for me still.
