### ISSUE TITLE
Image for postgres 10 is not on docker hub

### ISSUE THREAD

**Issue by stellamargonar** [clkao/docker-postgres-plv8#30]
Hi!
On [docker hub](https://hub.docker.com/r/clkao/postgres-plv8/) repo info is reported the tag for postgres 10, but it's missing in the actual list of [images tags](https://hub.docker.com/r/clkao/postgres-plv8/tags/)

in https://github.com/clkao/docker-postgres-plv8/pull/29 it's mentioned that @clkao should add it to docker hub in order to make it available

**Comment by eouw0o83hf** [comment]
+1 having this on dockerhub would be super helpful!

**Comment by karelg** [comment]
+1

**Comment by neemah** [comment]
+999999!

**Comment by ruimarinho** [comment]
@clkao seems like Docker Hub now supports adding collaborators as well. Can you give it a try?

**Comment by clkao** [comment]
@ruimarinho hey it seems you've already been a collaborator. I don't see any other role that can be switched on. what's not working for you?

**Comment by ruimarinho** [comment]
@clkao hey! You need to create an organization on Docker Hub and add me and yourself as team members, otherwise I cannot see the project there.

https://docs.docker.com/docker-hub/orgs/

**Comment by ruimarinho** [comment]
Were you able to do the conversion @clkao? As a collaborator I can only push or pull images, therefore I am unable to configure automated builds.

**Comment by clkao** [comment]
@ruimarinho just created the pgplv8 org, please see if you can configure builds

**Comment by ruimarinho** [comment]
@clkao unfortunately I am still unable to configure builds. The GitHub link does not show repositories I do not own, so this repository would have to be converted to an organization as well.

Would you mind doing that?

**Comment by ruimarinho** [comment]
I have pushed the image manually while @clkao sets up the organization on Docker Hub. 

`docker pull clkao/postgres-plv8:10-2`.
