### ISSUE TITLE
ERROR:  column "plv8" does not exist

### ISSUE THREAD

**Issue by firozmi** [clkao/docker-postgres-plv8#32]
![postgres](https://user-images.githubusercontent.com/17116664/43515719-e6014684-95a0-11e8-8c88-ae6389121679.png)
Followed the instructions in the dockerhub, only changing the image variant to 9.4-1.4

**Comment by ruimarinho** [comment]
Please take a look at the updated [README.md](https://github.com/clkao/docker-postgres-plv8/blob/master/README.md). A character was being incorrectly escaped.
