### ISSUE TITLE
IP address for Postgress

### ISSUE THREAD

**Issue by TBone242** [clkao/docker-postgres-plv8#33]
I've been trying connect to Postgres with PGAdmin using your Docker-Compose but won't connect to an IP address or Localhost. When I type in the command "docker ps", there's no address. When I inspect the config file (docker inspect name | grep "IPAdress") there's no address there.... in case there's something besides localhost or 127.0.0.1.

**Comment by ruimarinho** [comment]
You just need to map ports to your host or alternatively create a docker network and use that network to communicate between containers.
